# AUTO-GENERATED by sample_data/generate_sample_data.py — do not edit by hand.
# A synthetic 12-test pytest suite for an e-commerce/auth app. Each test is a
# runnable, self-contained stub asserting simple mocked logic (no external deps).
# Planted: a near-duplicate login pair; flakiness/slowness live in CI history;
# acceptance criterion AC-5 (password reset) has no test here -> coverage gap.

def test_login_success():
    """AC-1: a user with valid credentials is authenticated."""
    users = {"alice": "s3cret"}
    def login(username, password):
        return users.get(username) == password
    assert login("alice", "s3cret") is True
    assert login("alice", "wrong") is False

def test_login_valid_credentials():
    """AC-1: logging in with the correct password succeeds (near-duplicate of test_login_success)."""
    accounts = {"alice": "s3cret"}
    def authenticate(user, pwd):
        return accounts.get(user) == pwd
    # Same behaviour as test_login_success, different wording.
    assert authenticate("alice", "s3cret") is True

def test_logout():
    """AC-2: logging out ends the active session."""
    session = {"alice": True}
    def logout(user):
        session[user] = False
        return session[user]
    assert logout("alice") is False

def test_add_to_cart():
    """Adding items increases the cart item count."""
    cart = []
    def add_to_cart(item):
        cart.append(item)
        return len(cart)
    assert add_to_cart("sku-1") == 1
    assert add_to_cart("sku-2") == 2

def test_cart_total_includes_tax():
    """AC-3: the cart total includes tax."""
    def cart_total(subtotal, tax_rate=0.1):
        return round(subtotal * (1 + tax_rate), 2)
    assert cart_total(100.0) == 110.0

def test_checkout_creates_order():
    """AC-4: checking out a non-empty cart creates an order."""
    orders = []
    def checkout(cart):
        if not cart:
            raise ValueError("empty cart")
        order_id = len(orders) + 1
        orders.append({"id": order_id, "items": list(cart)})
        return order_id
    assert checkout(["sku-1"]) == 1
    assert len(orders) == 1

def test_payment_gateway_charges_card():
    """The payment gateway charges the card and returns a confirmation (slow integration in CI history)."""
    def charge(card_number, amount):
        return {"card": card_number[-4:], "amount": amount, "status": "charged"}
    result = charge("4111111111111234", 110.0)
    assert result["status"] == "charged"
    assert result["card"] == "1234"

def test_search_returns_results():
    """Searching the catalogue returns the matching products (flaky in CI history)."""
    catalogue = ["red shoes", "blue shoes", "red hat"]
    def search(query):
        return [p for p in catalogue if query in p]
    results = search("red")
    assert "red shoes" in results
    assert len(results) == 2

def test_remove_from_cart():
    """Removing an item drops it from the cart."""
    cart = ["sku-1", "sku-2"]
    def remove(item):
        cart.remove(item)
        return cart
    assert remove("sku-1") == ["sku-2"]

def test_apply_discount_code():
    """A valid discount code reduces the total; an unknown code does not."""
    def apply_discount(total, code):
        codes = {"SAVE10": 0.10}
        return round(total * (1 - codes.get(code, 0.0)), 2)
    assert apply_discount(100.0, "SAVE10") == 90.0
    assert apply_discount(100.0, "BOGUS") == 100.0

def test_product_listing_pagination():
    """Product listing paginates results into fixed-size pages."""
    products = list(range(1, 26))
    def paginate(items, page, size=10):
        start = (page - 1) * size
        return items[start:start + size]
    assert paginate(products, 1) == list(range(1, 11))
    assert len(paginate(products, 3)) == 5

def test_update_account_email():
    """Updating the account email validates and stores the new address."""
    account = {"email": "old@example.com"}
    def update_email(new_email):
        if "@" not in new_email:
            raise ValueError("invalid email")
        account["email"] = new_email
        return account["email"]
    assert update_email("new@example.com") == "new@example.com"
