# AUTO-GENERATED by sample_data/generate_sample_data.py — do not edit by hand.
# Checkout & payment tests (orders, payment, retries, confirmation).
# Each test is a runnable, self-contained pytest stub (no external deps).

def test_checkout_creates_order():
    """AC-4: checking out a non-empty cart creates an order."""
    orders = []
    def checkout(cart):
        if not cart:
            raise ValueError("empty cart")
        orders.append(cart)
        return len(orders)
    assert checkout(["sku-1"]) == 1

def test_payment_gateway_charges_card():
    """The payment gateway charges the card and returns a confirmation (slow integration; risk-area: payment)."""
    def charge(card, amount):
        return {"card": card[-4:], "amount": amount, "status": "charged"}
    r = charge("4111111111111234", 110.0)
    assert r["status"] == "charged" and r["card"] == "1234"

def test_checkout_payment_retry():
    """A failed payment is retried and eventually succeeds."""
    def pay(attempts):
        return "ok" if attempts >= 2 else "retry"
    assert pay(2) == "ok"
    assert pay(1) == "retry"

def test_order_confirmation_email():
    """An order confirmation message is queued after checkout."""
    queue = []
    def confirm(order_id):
        queue.append(order_id)
        return len(queue)
    assert confirm(1) == 1

def test_order_blocked_when_basket_empty():
    """An order cannot be placed when the basket is empty."""
    def place_order(basket):
        if not basket:
            return "blocked"
        return "ok"
    assert place_order([]) == "blocked"
