# AUTO-GENERATED by sample_data/generate_sample_data.py — do not edit by hand.
# Catalogue search tests (matching, empty results, export, pagination).
# Each test is a runnable, self-contained pytest stub (no external deps).

def test_search_returns_results():
    """AC-5: searching the catalogue returns the matching products (flaky in CI history)."""
    catalogue = ["red shoes", "blue shoes", "red hat"]
    def search(q):
        return [p for p in catalogue if q in p]
    assert "red shoes" in search("red")

def test_search_no_results():
    """Searching for an unknown term returns no products."""
    catalogue = ["red shoes"]
    def search(q):
        return [p for p in catalogue if q in p]
    assert search("laptop") == []

def test_full_catalog_export():
    """Exporting the full product catalogue returns every product (slow in CI history)."""
    catalogue = list(range(1, 6))
    def export_all():
        return list(catalogue)
    assert export_all() == [1, 2, 3, 4, 5]

def test_search_pagination():
    """Search results are paginated into fixed-size pages."""
    def page(items, n, size=10):
        return items[(n - 1) * size:(n - 1) * size + size]
    assert page(list(range(25)), 1) == list(range(10))
