# AUTO-GENERATED by sample_data/generate_sample_data.py — do not edit by hand.
# Authentication & session tests (login, logout, session, sign-up).
# Each test is a runnable, self-contained pytest stub (no external deps).

def test_login_success():
    """AC-1: logging in with valid credentials succeeds and authenticates the user."""
    users = {"alice": "s3cret"}
    def login(u, p):
        return users.get(u) == p
    assert login("alice", "s3cret") is True
    assert login("alice", "wrong") is False

def test_login_valid_credentials():
    """AC-1: logging in with valid credentials succeeds and authenticates the user. (near-duplicate of test_login_success)."""
    accounts = {"alice": "s3cret"}
    def authenticate(user, pwd):
        return accounts.get(user) == pwd
    assert authenticate("alice", "s3cret") is True

def test_logout():
    """AC-2: logging out ends the active session."""
    session = {"alice": True}
    def logout(user):
        session[user] = False
        return session[user]
    assert logout("alice") is False

def test_session_expiry():
    """An idle session expires after the timeout elapses."""
    def is_expired(idle_seconds, timeout=900):
        return idle_seconds >= timeout
    assert is_expired(1000) is True
    assert is_expired(10) is False

def test_weak_signup_rejected():
    """Weak credentials are rejected at sign-up."""
    def strong_enough(secret):
        return len(secret) >= 8
    assert strong_enough("longenough") is True
    assert strong_enough("abc") is False
