# AUTO-GENERATED by sample_data/generate_sample_data.py — do not edit by hand.
# Account-management tests (profile, email, deletion).
# Each test is a runnable, self-contained pytest stub (no external deps).

def test_update_account_email():
    """Updating the account email validates and stores the new address."""
    acct = {"email": "old@example.com"}
    def update(email):
        if "@" not in email:
            raise ValueError("invalid")
        acct["email"] = email
        return acct["email"]
    assert update("new@example.com") == "new@example.com"

def test_update_profile_name():
    """Updating the profile stores the new display name."""
    profile = {"name": "Alice"}
    def rename(name):
        profile["name"] = name
        return profile["name"]
    assert rename("Alicia") == "Alicia"

def test_delete_account():
    """Deleting an account removes the user record."""
    accounts = {"alice": {}}
    def delete(user):
        accounts.pop(user, None)
        return user not in accounts
    assert delete("alice") is True
