"""Golden-set end-to-end regression test — full pipeline vs the planted findings.

End-to-end: run the full graph on the sample_data/ suite, auto-answering the 3 HITL
interrupts, and assert the four outputs are produced and the audit_log is complete.

Also assert the run reproduces sample_data/expected_findings.json (the golden set):
the near-duplicate login cluster, the flaky test (test_search_returns_results), the slow
test (test_payment_gateway_charges_card), and the AC-5 coverage gap. This is regression
coverage on the agent's analysis quality, not just that it ran without crashing.

The golden file (generated by sample_data/generate_sample_data.py) uses the keys
`duplicates` / `flaky` / `slow` / `coverage_gaps`; the agent's output uses
`redundancy_flags` / `flakiness_flags` / `slow_flags` / `coverage_map` — these tests map
between the two.

Architecture position: tests/ = the safety net; this module is the golden-set regression.
Unlike the two blocker tests (which isolate one invariant), this drives the whole graph
end to end in automated mode and grades the four deliverables against the answer key that
generate_sample_data.py planted.

Called by: pytest.

Data in: reads sample_data/expected_findings.json (the golden set) at import; the run
reads the sample suite + criteria + CI history via the pipeline's tools.
Data out: none persisted (memory isolated by the conftest fixture); pure assertions.
"""

import json
from pathlib import Path

import pytest

from src.graph import build_graph

# WHY: load the golden answer key once at import — it is the single source of truth the run
# is graded against (generated from the same planted constants as the sample data, so it
# can never drift). It is read here ONLY by the test, never by the agent at runtime.
GOLDEN = json.loads(
    (Path(__file__).resolve().parents[1] / "sample_data" / "expected_findings.json")
    .read_text(encoding="utf-8")
)


@pytest.fixture(scope="module")
def outputs():
    """Run the full graph once on the sample suite and expose its final_outputs.

    Purpose: build and invoke the compiled graph in automated mode against the sample
        suite, returning the run's four deliverables for every assertion in this module.
    Inputs: none (constructs the initial state inline; scope="module" so the run executes
        once and is shared across tests).
    Outputs: the run's final_outputs dict (scorecard, coverage_gap_map,
        redundancy_flakiness_report, optimised_plan, plus audit_log etc.).
    Side effects: graph invocation — runs the entire pipeline (intake..report), reads the
        sample fixtures, spawns sandbox subprocesses for validation; memory writes are
        isolated to a temp dir by the conftest fixture.
    Called by: pytest (injected into every test in this module).
    Calls: build_graph, graph.invoke.
    """
    graph = build_graph()
    # WHY: thread_id namespaces this run's checkpoints under "e2e".
    cfg = {"configurable": {"thread_id": "e2e"}}
    # WHY: the automated-mode invoke — run_mode="automated" auto-approves the recommended
    # decision at each of the 3 HITL checkpoints, so the graph runs start-to-END with no
    # human input while still exercising the real removal/ranking/generation logic.
    state = graph.invoke({
        "project_id": "e2e",
        "suite_path": "sample_data/sample_suite",
        "optimization_goal": "speed",
        "coverage_target": 0.80,
        "risk_areas": ["payment"],
        "run_mode": "automated",      # auto-approves recommended at each checkpoint
        "gen_retry_count": 0,
        "audit_log": [], "tool_errors": [],
    }, config=cfg)
    return state["final_outputs"]


def test_four_deliverables_present(outputs):
    """Purpose: the run MUST emit all four non-empty deliverables.

    Validates that report_node produced scorecard, coverage_gap_map,
    redundancy_flakiness_report, and optimised_plan (each present and truthy).
    Inputs: the shared outputs fixture.
    Outputs: None; asserts each of the four keys exists and is non-empty.
    Side effects: None (pure).
    Called by: pytest.
    Calls: — (dict membership only).
    """
    # WHY: the product's contract is exactly four deliverables — assert each is present and
    # non-empty so a run that silently drops a section fails loudly.
    for key in ("scorecard", "coverage_gap_map",
                "redundancy_flakiness_report", "optimised_plan"):
        assert key in outputs and outputs[key]


def test_audit_log_is_complete(outputs):
    """Purpose: the audit trail MUST record every core pipeline node.

    Validates the append-only audit_log accumulated an entry from each headline node, so
    the run is fully traceable end to end.
    Inputs: the shared outputs fixture.
    Outputs: None; asserts each expected node name appears in the audit log.
    Side effects: None (pure).
    Called by: pytest.
    Calls: — (list comprehension only).
    """
    # WHY: every core node must have contributed to the append-only audit_log; a missing
    # node name means either the node didn't run or dropped its audit entry.
    events = [e["node"] for e in outputs["audit_log"]]
    for node in ("intake", "coverage", "redundancy", "scoring",
                 "prioritisation", "assemble", "report"):
        assert node in events


def test_reproduces_golden_duplicate_cluster(outputs):
    """Purpose: the agent MUST detect every planted near-duplicate cluster.

    Golden assertion (duplicates): each pair in GOLDEN["duplicates"] must appear as a
    redundancy cluster in the run's output. Maps golden `duplicates[].tests` to the agent's
    `redundancy_flags[].cluster`.
    Inputs: the shared outputs fixture and the GOLDEN key.
    Outputs: None; asserts each golden duplicate pair is a detected cluster.
    Side effects: None (pure).
    Called by: pytest.
    Calls: set.
    """
    # WHY: compare as sets so cluster ordering doesn't matter — every planted duplicate
    # pair must show up among the detected redundancy clusters.
    clusters = [set(f["cluster"])
                for f in outputs["redundancy_flakiness_report"]["redundancy_flags"]]
    for dup in GOLDEN["duplicates"]:
        assert set(dup["tests"]) in clusters


def test_reproduces_golden_flaky_and_slow(outputs):
    """Purpose: the agent MUST flag every planted flaky and slow test.

    Golden assertion (flaky + slow): each test in GOLDEN["flaky"]/["slow"] must appear in
    the run's flakiness_flags/slow_flags. Maps golden `test` ids to the agent's `test_id`.
    Inputs: the shared outputs fixture and the GOLDEN key.
    Outputs: None; asserts every golden flaky/slow id is flagged.
    Side effects: None (pure).
    Called by: pytest.
    Calls: set comprehensions.
    """
    report = outputs["redundancy_flakiness_report"]
    # WHY: collect the flagged ids into sets so membership checks are O(1) and order-free.
    flaky = {f["test_id"] for f in report["flakiness_flags"]}
    slow = {f["test_id"] for f in report["slow_flags"]}
    for f in GOLDEN["flaky"]:
        assert f["test"] in flaky
    for s in GOLDEN["slow"]:
        assert s["test"] in slow


def test_reproduces_golden_coverage_map_and_gap(outputs):
    """Purpose: the agent MUST detect planted gaps and cover every non-gap criterion.

    Golden assertion (coverage): every criterion in GOLDEN["coverage_gaps"] is reported as
    a gap with an empty coverage_map entry, and every OTHER criterion is covered by at
    least one test.
    Inputs: the shared outputs fixture and the GOLDEN key.
    Outputs: None; asserts gap detection and non-gap coverage.
    Side effects: None (pure).
    Called by: pytest.
    Calls: set/dict comprehensions.
    """
    cgm = outputs["coverage_gap_map"]
    detected_gaps = {g["criterion_id"] for g in cgm["gaps"]}
    golden_gaps = {g["criterion_id"] for g in GOLDEN["coverage_gaps"]}
    # WHY: every planted gap must be detected AND have no covering test (empty list) — a
    # gap with a linked test would be a false negative on the planted requirement.
    for gid in golden_gaps:
        assert gid in detected_gaps
        assert cgm["coverage_map"].get(gid) == []
    # WHY: the flip side — every non-gap criterion must be covered by at least one test, so
    # the matcher isn't just reporting everything as a gap.
    others = {cid: tests for cid, tests in cgm["coverage_map"].items() if cid not in golden_gaps}
    assert others and all(len(tests) >= 1 for tests in others.values())


def test_coverage_floor_held_and_no_pinned_removed(outputs):
    """Purpose: the final plan MUST honour the coverage floor and the risk-area pin.

    Golden assertion (safety): the proposed plan's projected coverage stays at/above the
    0.80 target (coverage-floor gate held through the full run), and the risk-pinned payment
    test is never in the removed set.
    Inputs: the shared outputs fixture.
    Outputs: None; asserts projected_coverage >= target and the pinned test is not removed.
    Side effects: None (pure).
    Called by: pytest.
    Calls: — (dict access / membership only).
    """
    plan = outputs["optimised_plan"]
    # WHY: end-to-end proof of Blocker #2 — the assembled plan never dips below the floor.
    assert plan["projected_coverage"] >= 0.80
    # WHY: risk_areas=["payment"] pins the payment test — end-to-end proof it is never
    # proposed for removal even after removals/revise ran unattended.
    assert "test_payment_gateway_charges_card" not in plan["proposed"]["removed"]
