# AUTO-GENERATED by sample_data/generate_sample_data.py — do not edit by hand.
# Shopping-cart tests (add, remove, totals, discounts, persistence).
# Each test is a runnable, self-contained pytest stub (no external deps).

def test_add_item_to_cart():
    """Adding an item to the cart increases the cart item count by one."""
    cart = []
    def add(item):
        cart.append(item)
        return len(cart)
    assert add("sku-1") == 1

def test_cart_add_item():
    """Adding an item to the cart increases the cart item count by one. (near-duplicate of test_add_item_to_cart)."""
    items = []
    def add_to_cart(sku):
        items.append(sku)
        return len(items)
    assert add_to_cart("sku-9") == 1

def test_remove_item_from_cart():
    """Removing an item drops it from the cart."""
    cart = ["sku-1", "sku-2"]
    def remove(item):
        cart.remove(item)
        return cart
    assert remove("sku-1") == ["sku-2"]

def test_cart_total_includes_tax():
    """AC-3: the cart total includes tax."""
    def cart_total(subtotal, tax_rate=0.1):
        return round(subtotal * (1 + tax_rate), 2)
    assert cart_total(100.0) == 110.0

def test_apply_discount_code():
    """A valid discount code reduces the cart total."""
    def apply(total, code):
        return round(total * (1 - {"SAVE10": 0.10}.get(code, 0.0)), 2)
    assert apply(100.0, "SAVE10") == 90.0
    assert apply(100.0, "NOPE") == 100.0

def test_cart_persists_between_visits():
    """The cart is restored when the user returns."""
    store = {"alice": ["sku-1"]}
    def restore(user):
        return store.get(user, [])
    assert restore("alice") == ["sku-1"]
